# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 

ifdef CONFIG_XPL_BUILD
obj-y := spl.o ice40.o strap_decode.o ../common/parse_gpio_straps.o ../common/rtc_workaround.o
else
obj-y  := ts4900.o strap_decode.o ../common/parse_gpio_straps.o ../common/rtc_workaround.o ../common/bbdetect.o
endif
